# Generated by Django 5.0.3 on 2024-04-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0004_news_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
